### ISSUE TITLE
API Key configuration.

### ISSUE THREAD

**Issue by nasim31** [KarthikGangadhar/CricApi#1]
Hi Karthik,
Can you please post some helpful steps on your gem implementation ?
Please help me where to configure these parameters?
require 'CricApi'
api_key = "TESTKEY0273"
cricapi = CricApi::Request.new(api_key)

**Comment by KarthikGangadhar** [comment]
@nasim31 , Its explained in detail here in the [documentation](https://www.rubydoc.info/gems/CricApi/0.2.2). You need to install the gem and then have to follow the step. 
 
1. Require  the gem in any `controller`, `model` or `helper`  where you want to use.
```
    require 'CricApi'
```
2. create instance of CrciApi by providing key as below.
```
    api_key = "TESTKEY0273" // you need to add your key
    cricapi = CricApi::Request.new(api_key) 
```
3. Then call the interested method as below.
```
   cricapi.cricket
```

**Comment by KarthikGangadhar** [comment]
I am closing this issue as resolved. let me know if you have any concern.
